#!/bin/ash
set -eu

cd /usr/src/app
redis-server --bind 127.0.0.1 --save "" --appendonly no --daemonize yes --logfile /tmp/redis.log
bundle exec rails db:prepare:with_data >/tmp/myminifactory-test-db.log 2>&1 || {
  cat /tmp/myminifactory-test-db.log
  exit 1
}
exec bundle exec rails runner /plugins/manyfold_myminifactory/test/plugin_test.rb
